### PR TITLE
Add offerwall mention to incompatible GPU message

### PR DESCRIPTION
**Pull request by VukAnd**

### CODE REVIEW

**Comment by dsarfati** [comment]
This is a great suggestion, we are already working on an updated page that gives users more information. I'll merge this in for now, but it will likely be replaced in the coming few weeks 😃

**Comment by VukAnd** [comment]
I'm fine with that! (considering it's not any huge rewrite or something, just some text)

**Comment by JaredCarpenterSalad** [comment]
Hey @VukAnd - we're working on the Salad Newsletter and wanted to cover your community submission and work on Github for us. Would you mind if we talked about your contribution and linked to your Github profile in the email? 

Thanks for your help! We appreciate it!

**Comment by VukAnd** [comment]
@JaredCarpenterSalad Go ahead!

**Pull request merged**
